db.getCollection('alimentos').insert({"idAlimento": NumberInt(638), "nombre": "Leche de almendras","estado": "","cal": 17,"pr": 0.62,"gr": 1.46,"hc": 0.57})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(639), "nombre": "Pistachos","estado": "","cal": 557,"pr": 20.61,"gr": 44.44,"hc": 27.97})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(640), "nombre": "Tofu","estado": "","cal": 78,"pr": 7.82,"gr": 4.93,"hc": 2.08})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(641), "nombre": "Semillas de lino","estado": "","cal": 534,"pr": 18.29,"gr": 42.16,"hc": 28.88})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(642), "nombre": "Harina de garbanzos","estado": "","cal": 387,"pr": 22.39,"gr": 6.69,"hc": 57.82})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(643), "nombre": "Pasta de tomate","estado": "","cal": 82,"pr": 4.32,"gr": 0.47,"hc": 18.91})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(644), "nombre": "Harissa","estado": "","cal": 72,"pr": 2.9,"gr": 1.2,"hc": 11})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(645), "nombre": "Pan integral","estado": "","cal": 246,"pr": 9.7,"gr": 4.2,"hc": 46.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(646), "nombre": "Cereales integrales","estado": "","cal": 358,"pr": 11.35,"gr": 2.4,"hc": 76.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(647), "nombre": "Mermelada","estado": "","cal": 260,"pr": 0.54,"gr": 0.14,"hc": 66.63})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(648), "nombre": "Pechuga de pavo","estado": "","cal": 104,"pr": 17.07,"gr": 1.66,"hc": 4.21})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(649), "nombre": "Galletas de trigo integral","estado": "","cal": 443,"pr": 8.8,"gr": 17.2,"hc": 68.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(650), "nombre": "Galletas de Chocolate","estado": "","cal": 45,"pr": 0.58,"gr": 1.54,"hc": 7.33})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(651), "nombre": "Galletas de avena","estado": "","cal": 450,"pr": 6.2,"gr": 18.1,"hc": 68.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(652), "nombre": "Tortitas de arroz integral","estado": "","cal": 29,"pr": 0.6,"gr": 0.2,"hc": 6.2})