db.getCollection('alimentos').insert({"idAlimento": NumberInt(1),"nombre": "Arroz","estado": "descasac.","cal": 355,"pr": 8.2,"gr": 0.6,"hc": 77})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(2),"nombre": "Arroz","estado": "hervido","cal": 126,"pr": 2.3,"gr": 0.2,"hc": 31.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(3),"nombre": "Arroz","estado": "paella","cal": 320,"pr": 6.9,"gr": 0.4,"hc": 74.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(4),"nombre": "avena","estado": "grano","cal": 384,"pr": 14.3,"gr": 7.7,"hc": 65.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(5),"nombre": "cebada","estado": "grano ","cal": 355,"pr": 8.6,"gr": 1.4,"hc": 78.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(6),"nombre": "cebada","estado": "hervida","cal": 125,"pr": 2.6,"gr": 0.6,"hc": 27.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(7),"nombre": "centeno","estado": "grano","cal": 341,"pr": 8.2,"gr": 1.6,"hc": 75})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(8),"nombre": "maiz","estado": "grano","cal": 364,"pr": 9.6,"gr": 3.5,"hc": 73.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(9),"nombre": "trigo","estado": "grano","cal": 356,"pr": 10.8,"gr": 2.3,"hc": 75})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(10),"nombre": "amidon de arroz","estado": "grano","cal": 353,"pr": 0.8,"gr": 0,"hc": 85.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(11),"nombre": "almidon de maiz","estado": "grano","cal": 364,"pr": 0.4,"gr": 0.2,"hc": 86.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(12),"nombre": "almidon de trigo","estado": "grano","cal": 352,"pr": 1.1,"gr": 0.2,"hc": 84.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(13),"nombre": "harina de arroz","estado": "grano","cal": 361,"pr": 7.4,"gr": 0.6,"hc": 79})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(14),"nombre": "harina de avena","estado": "grano","cal": 402,"pr": 13.2,"gr": 7.7,"hc": 70.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(15),"nombre": "harina de avena","estado": "copos","cal": 368,"pr": 6.7,"gr": 0.9,"hc": 84.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(16),"nombre": "harina de cebada","estado": "cruda","cal": 359,"pr": 9.1,"gr": 14.5,"hc": 76.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(17),"nombre": "harina de centeno","estado": "cruda","cal": 354,"pr": 10,"gr": 1.1,"hc": 74.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(18),"nombre": "harina de maiz","estado": "cruda","cal": 362,"pr": 9.2,"gr": 3.1,"hc": 72.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(19),"nombre": "harina de trigo integral","estado": "","cal": 339,"pr": 13.7,"gr": 1.87,"hc": 72.57})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(20),"nombre": "harina de trigo","estado": "","cal": 341,"pr": 9.86,"gr": 1.2,"hc": 70.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(21),"nombre": "harina de trigo","estado": "segunda","cal": 355,"pr": 10.1,"gr": 1.2,"hc": 78})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(22),"nombre": "harina trigo manitoba","estado": "1","cal": 339,"pr": 13.6,"gr": 2.5,"hc": 69.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(23),"nombre": "harina trigo manitoba","estado": "0,85","cal": 350,"pr": 13.4,"gr": 1.5,"hc": 72})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(24),"nombre": "harina trigo manitoba","estado": "0,8","cal": 350,"pr": 13.2,"gr": 1.4,"hc": 73.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(25),"nombre": "Pan rallado","estado": "","cal": 395,"pr": 13.35,"gr": 5.3,"hc": 71.98})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(26),"nombre": "Tallarines","estado": "","cal": 344,"pr": 12,"gr": 2,"hc": 68})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(27),"nombre": "Macarrones","estado": "","cal": 220,"pr": 8.06,"gr": 1.29,"hc": 42.95})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(28),"nombre": "Espaguetis","estado": "","cal": 220,"pr": 8.06,"gr": 1.29,"hc": 42.95})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(29),"nombre": "pan de avena","estado": "natural","cal": 212,"pr": 7.6,"gr": 1.5,"hc": 40.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(30),"nombre": "pan de debada","estado": "natural","cal": 198,"pr": 6.4,"gr": 1.1,"hc": 39.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(31),"nombre": "pan de centeno","estado": "natural","cal": 232,"pr": 6.5,"gr": 0.9,"hc": 47.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(32),"nombre": "pan dediabeticos","estado": "natural","cal": 235,"pr": 8.7,"gr": 0.7,"hc": 47.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(33),"nombre": "pan de maiz","estado": "natural","cal": 227,"pr": 6.4,"gr": 1.9,"hc": 43.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(34),"nombre": "pan de trigo","estado": "natural","cal": 241,"pr": 8.9,"gr": 1.6,"hc": 36.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(35),"nombre": "pan de trigo","estado": "moreno","cal": 246,"pr": 8.4,"gr": 1.9,"hc": 37})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(36),"nombre": "pan de trigo","estado": "blanco","cal": 262,"pr": 8.2,"gr": 1.3,"hc": 35.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(37),"nombre": "pan de trigo","estado": "blanco tostado","cal": 314,"pr": 9.4,"gr": 0.9,"hc": 20})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(38),"nombre": "pan de trigo","estado": "blanco frito","cal": 542,"pr": 7.2,"gr": 37.2,"hc": 4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(39),"nombre": "pan de viena","estado": "0","cal": 265,"pr": 8.2,"gr": 2.2,"hc": 33})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(40),"nombre": "buñuelos","estado": "fritos","cal": 408,"pr": 6.3,"gr": 20.1,"hc": 20.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(41),"nombre": "galletas","estado": "natural","cal": 435,"pr": 7.4,"gr": 13,"hc": 5.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(42),"nombre": "polvo para flanes","estado": "0","cal": 353,"pr": 0.5,"gr": 0.7,"hc": 8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(43),"nombre": "sagú","estado": "natural","cal": 348,"pr": 1.8,"gr": 0.2,"hc": 14.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(44),"nombre": "semola","estado": "natural","cal": 349,"pr": 9.8,"gr": 1.4,"hc": 12.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(45),"nombre": "soja","estado": "harina","cal": 440,"pr": 43,"gr": 22,"hc": 7.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(46),"nombre": "tapioca","estado": "natural","cal": 350,"pr": 0.6,"gr": 0.2,"hc": 12.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(47),"nombre": "tarta manzana","estado": "natural","cal": 250,"pr": 2.1,"gr": 9.1,"hc": 38})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(48),"nombre": "almortas","estado": "crudos","cal": 328,"pr": 27.8,"gr": 1.1,"hc": 10})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(49), "nombre": "garbanzos","estado": "crudos","cal": 355,"pr": 21.8,"gr": 5.1,"hc": 12.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(50),"nombre": "garbanzos","estado": "cocidos","cal": 150,"pr": 10.2,"gr": 5,"hc": 65})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(51),"nombre": "guisantes frescos","estado": "crudos","cal": 98,"pr": 7.2,"gr": 0.4,"hc": 73.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(52),"nombre": "guisantes frescos","estado": "cocidos","cal": 68,"pr": 4,"gr": 0.3,"hc": 85})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(53),"nombre": "guisantes secos","estado": "crudos","cal": 323,"pr": 23.5,"gr": 1.8,"hc": 9.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(54),"nombre": "guisantes secos","estado": "hervidos","cal": 77,"pr": 6.9,"gr": 0,"hc": 73.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(55),"nombre": "guisantes secos","estado": "conserva","cal": 91,"pr": 5.9,"gr": 0,"hc": 73.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(56),"nombre": "habas","estado": "crudos","cal": 315,"pr": 29.4,"gr": 1.5,"hc": 14.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(57),"nombre": "habas","estado": "cocidos","cal": 108,"pr": 7.1,"gr": 0.9,"hc": 70.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(58),"nombre": "judias blancas","estado": "crudas","cal": 320,"pr": 20.8,"gr": 1.7,"hc": 62.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(59),"nombre": "judias blancas","estado": "cocidas ","cal": 99,"pr": 7.6,"gr": 0.8,"hc": 18.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(60),"nombre": "judias rojas","estado": "crudas","cal": 332,"pr": 20.1,"gr": 1.5,"hc": 63.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(61),"nombre": "judias rojas","estado": "cocidas ","cal": 92,"pr": 6.6,"gr": 0.4,"hc": 16.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(62),"nombre": "lentejas secas","estado": "crudas","cal": 339,"pr": 23.7,"gr": 1.2,"hc": 62.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(63),"nombre": "lentejas secas","estado": "cocidas ","cal": 102,"pr": 7.1,"gr": 0.3,"hc": 19.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(64),"nombre": "soja fresca","estado": "crudas","cal": 135,"pr": 13.9,"gr": 4.8,"hc": 10.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(65),"nombre": "Salsa de soja","estado": "","cal": 53,"pr": 6.28,"gr": 0.04,"hc": 7.61})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(66),"nombre": "acederas","estado": "crudas","cal": 18,"pr": 2.5,"gr": 0.4,"hc": 2.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(67),"nombre": "acederas","estado": "cocidas ","cal": 5,"pr": 0.9,"gr": 0.1,"hc": 1.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(68),"nombre": "acelgas ","estado": "crudas","cal": 18,"pr": 1.9,"gr": 0.3,"hc": 2.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(69),"nombre": "acelgas ","estado": "cocidas ","cal": 5,"pr": 0.36,"gr": 0,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(70),"nombre": "achicoria","estado": "cruda","cal": 16,"pr": 1.2,"gr": 0.2,"hc": 2.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(71),"nombre": "achicoria","estado": "tostada ","cal": 280,"pr": 28.1,"gr": 2,"hc": 42})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(72),"nombre": "ajo","estado": "","cal": 149,"pr": 6.36,"gr": 0.5,"hc": 33.06})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(73),"nombre": "alcachofa","estado": "cruda","cal": 67,"pr": 3,"gr": 0.8,"hc": 18.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(74),"nombre": "alcachofa","estado": "cocidas ","cal": 16,"pr": 1.1,"gr": 0.2,"hc": 3.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(75),"nombre": "apio","estado": "crudos","cal": 19,"pr": 1.2,"gr": 0.2,"hc": 4.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(76),"nombre": "apio","estado": "cocidos","cal": 9.5,"pr": 1,"gr": 0.15,"hc": 2.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(77),"nombre": "batata","estado": "cruda","cal": 127,"pr": 2.1,"gr": 0.6,"hc": 29.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(78),"nombre": "batata","estado": "cocidas ","cal": 98,"pr": 1.7,"gr": 0.5,"hc": 26})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(79),"nombre": "berenjena","estado": "cruda","cal": 19,"pr": 1.2,"gr": 0.2,"hc": 4.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(80),"nombre": "berenjena","estado": "cocidas ","cal": 10,"pr": 1.1,"gr": 0,"hc": 2.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(81),"nombre": "berros","estado": "crudos","cal": 25,"pr": 2.1,"gr": 0.3,"hc": 47.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(82),"nombre": "brocoli","estado": "crudos","cal": 29,"pr": 3.2,"gr": 0.2,"hc": 4.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(83),"nombre": "brocoli","estado": "cocidos","cal": 17,"pr": 1.3,"gr": 0.13,"hc": 4.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(84),"nombre": "calabaza","estado": "cruda","cal": 28,"pr": 0.7,"gr": 0.1,"hc": 6.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(85),"nombre": "calabaza","estado": "cocidas ","cal": 21,"pr": 1.08,"gr": 0.22,"hc": 4.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(86),"nombre": "calabacin","estado": "crudo ","cal": 23,"pr": 4.2,"gr": 0.1,"hc": 7.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(87),"nombre": "calabacin","estado": "cocidos","cal": 6,"pr": 0.9,"gr": 0,"hc": 1.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(88),"nombre": "cardo","estado": "crudo","cal": 24,"pr": 2.3,"gr": 0.3,"hc": 5.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(89),"nombre": "cardo","estado": "cocidos","cal": 17,"pr": 1.4,"gr": 0.2,"hc": 3.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(90),"nombre": "cardillo","estado": "crudo","cal": 15,"pr": 1.05,"gr": 0,"hc": 5.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(91),"nombre": "cardillo","estado": "cocidos","cal": 10,"pr": 0.7,"gr": 0,"hc": 2.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(92),"nombre": "cebolla","estado": "crudo","cal": 38,"pr": 1.3,"gr": 0.2,"hc": 8.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(93),"nombre": "cebolla","estado": "cocidas ","cal": 20.2,"pr": 0.4,"gr": 0.2,"hc": 4.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(94),"nombre": "Cebolla","estado": "frita","cal": 335,"pr": 1.8,"gr": 33.3,"hc": 13.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(95),"nombre": "col","estado": "cruda","cal": 28,"pr": 1.7,"gr": 0.2,"hc": 6.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(96),"nombre": "col","estado": "cocidas ","cal": 15,"pr": 1.3,"gr": 0.1,"hc": 2.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(97),"nombre": "col","estado": "acida","cal": 23,"pr": 1.4,"gr": 0.3,"hc": 4.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(98),"nombre": "col debruselas","estado": "cruda","cal": 42,"pr": 3.8,"gr": 0.5,"hc": 8.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(99),"nombre": "col debruselas","estado": "cocidas ","cal": 20,"pr": 3.1,"gr": 0.4,"hc": 5.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(100),"nombre": "col rizada","estado": "cruda","cal": 33,"pr": 3.2,"gr": 0.4,"hc": 5.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(101),"nombre": "coliflor","estado": "cruda","cal": 28,"pr": 2.3,"gr": 0.2,"hc": 5.04})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(102),"nombre": "coliflor","estado": "cocida crudo","cal": 20,"pr": 1.9,"gr": 0.7,"hc": 3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(103),"nombre": "colinabo","estado": "crudo","cal": 33,"pr": 2.2,"gr": 0.1,"hc": 6.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(104),"nombre": "champiñon","estado": "crudo","cal": 27,"pr": 3.7,"gr": 0.2,"hc": 3.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(105),"nombre": "chirivia","estado": "crudo","cal": 5.8,"pr": 1.5,"gr": 0.5,"hc": 13.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(106),"nombre": "chirivia","estado": "cocidos","cal": 34,"pr": 1.1,"gr": 0.4,"hc": 8.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(107),"nombre": "escarola","estado": "crudo","cal": 20,"pr": 1.6,"gr": 0.2,"hc": 4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(108),"nombre": "esparragos","estado": "crdudos","cal": 25,"pr": 2.3,"gr": 0.2,"hc": 4.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(109),"nombre": "esparragos","estado": "cocidos","cal": 20,"pr": 2.1,"gr": 0.2,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(110),"nombre": "espinacas","estado": "crudas","cal": 26,"pr": 2.5,"gr": 0.3,"hc": 4.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(111),"nombre": "espinacas","estado": "cocidas ","cal": 20,"pr": 2.2,"gr": 0.2,"hc": 5.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(112),"nombre": "judias verdes","estado": "crudas","cal": 35,"pr": 2.3,"gr": 0.2,"hc": 6.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(113),"nombre": "judias verdes","estado": "cocidas ","cal": 15,"pr": 1,"gr": 0.1,"hc": 3.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(114),"nombre": "lechuga","estado": "crudas","cal": 17,"pr": 1.2,"gr": 0.2,"hc": 2.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(115),"nombre": "lombarda","estado": "crudas","cal": 35,"pr": 2.6,"gr": 0.15,"hc": 5.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(116),"nombre": "lombarda","estado": "cocida","cal": 10,"pr": 1.1,"gr": 0,"hc": 2.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(117),"nombre": "mostaza","estado": "cruda","cal": 20,"pr": 2.1,"gr": 0.3,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(118),"nombre": "nabos","estado": "crudos","cal": 30,"pr": 1.8,"gr": 0.3,"hc": 5.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(119),"nombre": "nabos","estado": "cocidos","cal": 21,"pr": 1.3,"gr": 0.2,"hc": 4.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(120),"nombre": "patata","estado": "cruda","cal": 85,"pr": 2.1,"gr": 0.2,"hc": 19})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(121),"nombre": "patata","estado": "cocida","cal": 65,"pr": 1.7,"gr": 0.3,"hc": 15.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(122),"nombre": "patata","estado": "asada","cal": 110,"pr": 2.6,"gr": 0.7,"hc": 29.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(123),"nombre": "patata","estado": "frita","cal": 230,"pr": 3.3,"gr": 10.6,"hc": 30.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(124),"nombre": "patata","estado": "pure","cal": 121,"pr": 1.8,"gr": 5.5,"hc": 16.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(125),"nombre": "patata","estado": "almidon","cal": 350,"pr": 1.8,"gr": 0.9,"hc": 81.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(126),"nombre": "pepino","estado": "crudo","cal": 10,"pr": 0.7,"gr": 0.15,"hc": 2.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(127),"nombre": "perejil","estado": "crudo","cal": 36,"pr": 2.97,"gr": 0.79,"hc": 6.33})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(128),"nombre": "pimienta","estado": "crudo","cal": 255,"pr": 10.95,"gr": 3.26,"hc": 64.81})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(129),"nombre": "pimiento rojo","estado": "crudo","cal": 27,"pr": 1.3,"gr": 0.6,"hc": 7.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(130),"nombre": "pimiento del piquillo","estado": "crudos","cal": 44,"pr": 0.8,"gr": 0.2,"hc": 9.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(131),"nombre": "puerros","estado": "crudo","cal": 37,"pr": 2.8,"gr": 0.35,"hc": 7.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(132),"nombre": "puerros","estado": "cocidos","cal": 25,"pr": 2.3,"gr": 0,"hc": 4.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(133),"nombre": "rabanos","estado": "crudo","cal": 18,"pr": 1.2,"gr": 0.1,"hc": 3.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(134),"nombre": "remolacha","estado": "cruda","cal": 43,"pr": 1.8,"gr": 0.1,"hc": 10.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(135),"nombre": "remolacha","estado": "cocida","cal": 35,"pr": 1.9,"gr": 0.1,"hc": 8.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(136),"nombre": "Pollo (muslo)","estado": "crudo","cal": 119,"pr": 19.65,"gr": 3.91,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(137),"nombre": "Sirope de arce","estado": "","cal": 261,"pr": 0,"gr": 0.2,"hc": 67.09})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(138),"nombre": "seta","estado": "cruda","cal": 17,"pr": 1.9,"gr": 0.3,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(139),"nombre": "seta","estado": "frita","cal": 217,"pr": 2.2,"gr": 24.3,"hc": 5.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(140),"nombre": "tomate","estado": "crudo","cal": 18,"pr": 0.88,"gr": 0.2,"hc": 3.92})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(141),"nombre": "tomate","estado": "cocido","cal": 19,"pr": 1,"gr": 0.1,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(142),"nombre": "tomate","estado": "frito","cal": 73,"pr": 2.3,"gr": 6.2,"hc": 4.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(143),"nombre": "tomate","estado": "jugo","cal": 18,"pr": 0.8,"gr": 1.2,"hc": 3.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(144),"nombre": "trufa","estado": "fresca","cal": 63,"pr": 7.6,"gr": 0.5,"hc": 6.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(145),"nombre": "trufa","estado": "seca","cal": 260,"pr": 36.9,"gr": 2,"hc": 28.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(146),"nombre": "verduras (medio)","estado": "crudas","cal": 23,"pr": 1.3,"gr": 0.2,"hc": 38})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(147),"nombre": "zanahoria","estado": "cruda","cal": 40,"pr": 1.1,"gr": 0.3,"hc": 8.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(148),"nombre": "zanahoria","estado": "cocida","cal": 27,"pr": 0.8,"gr": 0.4,"hc": 6.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(149),"nombre": "aceitunas verdes","estado": "","cal": 181,"pr": 2.9,"gr": 24.8,"hc": 4.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(150),"nombre": "albaricoque","estado": "crudo","cal": 45,"pr": 0.8,"gr": 0.6,"hc": 9.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(151),"nombre": "albaricoque","estado": "conserva","cal": 72,"pr": 0.5,"gr": 0.3,"hc": 18})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(152),"nombre": "albaricoque","estado": "jugo","cal": 50,"pr": 0.45,"gr": 0.7,"hc": 11.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(153),"nombre": "arandano","estado": "crudo","cal": 53,"pr": 0.8,"gr": 0.6,"hc": 13.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(154),"nombre": "cerezas","estado": "crudas","cal": 65,"pr": 1.3,"gr": 0.6,"hc": 15.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(155),"nombre": "cerezas","estado": "cocidas","cal": 23,"pr": 0.8,"gr": 0.4,"hc": 9.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(156),"nombre": "ciruelas","estado": "crudas","cal": 58,"pr": 0.75,"gr": 0.3,"hc": 15.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(157),"nombre": "ciruelas","estado": "crudas","cal": 71,"pr": 0.4,"gr": 0,"hc": 19.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(158),"nombre": "frambuesas","estado": "crudas","cal": 45,"pr": 1.1,"gr": 0.5,"hc": 11.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(159),"nombre": "frambuesas","estado": "crudas","cal": 38,"pr": 0.2,"gr": 0,"hc": 10.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(160),"nombre": "fresa","estado": "jugop","cal": 40,"pr": 0.8,"gr": 0.6,"hc": 8.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(161),"nombre": "freson","estado": "crudas","cal": 25,"pr": 1.8,"gr": 0.1,"hc": 5.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(162),"nombre": "granada","estado": "crudas","cal": 60,"pr": 2.5,"gr": 0.8,"hc": 16.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(163),"nombre": "grosella","estado": "crudas","cal": 42,"pr": 1.3,"gr": 0.2,"hc": 9.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(164),"nombre": "guindas","estado": "crudas","cal": 55,"pr": 0.66,"gr": 0,"hc": 13.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(165),"nombre": "higo comun","estado": "crudas","cal": 69,"pr": 1.3,"gr": 0.4,"hc": 16.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(166),"nombre": "limon","estado": "crudas","cal": 36,"pr": 1,"gr": 1.5,"hc": 9.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(167),"nombre": "limon","estado": "crua","cal": 25,"pr": 0.5,"gr": 0.3,"hc": 8.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(168),"nombre": "majuela","estado": "zumo","cal": 131,"pr": 4.1,"gr": 0,"hc": 24.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(169),"nombre": "mandarina","estado": "jugo","cal": 33,"pr": 1.2,"gr": 0.9,"hc": 10.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(170),"nombre": "mango","estado": "crudos","cal": 66,"pr": 0.7,"gr": 0.2,"hc": 17.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(171),"nombre": "manzana","estado": "crudos","cal": 52,"pr": 0.3,"gr": 0.4,"hc": 13.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(172),"nombre": "manzana","estado": "crudo","cal": 102,"pr": 0.8,"gr": 0.5,"hc": 27})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(173),"nombre": "manzana","estado": "asada","cal": 52,"pr": 0.5,"gr": 0,"hc": 13.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(174),"nombre": "melocoton","estado": "jugo","cal": 48,"pr": 0.7,"gr": 0.2,"hc": 12.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(175),"nombre": "melocoton","estado": "crudo","cal": 68,"pr": 0.4,"gr": 0.1,"hc": 18.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(176),"nombre": "melocoton","estado": "conserva","cal": 49.6,"pr": 0.32,"gr": 0.1,"hc": 13.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(177),"nombre": "melon","estado": "jugo","cal": 29,"pr": 0.4,"gr": 0.2,"hc": 6.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(178),"nombre": "membrillo","estado": "crudo","cal": 42,"pr": 0.6,"gr": 0.93,"hc": 11.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(179),"nombre": "mora","estado": "crudo","cal": 56,"pr": 1.1,"gr": 0.9,"hc": 10.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(180),"nombre": "mora","estado": "crudo","cal": 15,"pr": 0.7,"gr": 0,"hc": 3.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(181),"nombre": "mora","estado": "cocidas","cal": 32,"pr": 3,"gr": 0,"hc": 7.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(182),"nombre": "Naranja","estado": "","cal": 62,"pr": 1.23,"gr": 0.16,"hc": 15.39})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(183),"nombre": "Naranja","estado": "zumo","cal": 112,"pr": 1.74,"gr": 0.5,"hc": 25.79})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(184),"nombre": "nispero","estado": "zumo","cal": 80,"pr": 0.8,"gr": 0.8,"hc": 22.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(185),"nombre": "peras","estado": "crudo","cal": 58,"pr": 0.7,"gr": 0.4,"hc": 16.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(186),"nombre": "peras","estado": "crudos","cal": 90,"pr": 1.3,"gr": 0,"hc": 22.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(187),"nombre": "peras","estado": "asadas","cal": 75,"pr": 0.8,"gr": 0.1,"hc": 25.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(188),"nombre": "peras","estado": "conserva","cal": 51,"pr": 0.3,"gr": 0.08,"hc": 13.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(189),"nombre": "piña","estado": "nectar","cal": 51,"pr": 0.45,"gr": 0.2,"hc": 13.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(190),"nombre": "piña","estado": "crudas","cal": 76,"pr": 0.4,"gr": 0.1,"hc": 19.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(191),"nombre": "piña","estado": "conserva","cal": 51,"pr": 0.3,"gr": 0.1,"hc": 13.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(192),"nombre": "platano","estado": "jugo crudo","cal": 91,"pr": 1.2,"gr": 0.3,"hc": 21.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(193),"nombre": "ruibardo","estado": "crudo","cal": 16,"pr": 0.5,"gr": 0.1,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(194),"nombre": "sandia","estado": "crudo","cal": 31,"pr": 0.5,"gr": 0.2,"hc": 6.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(195),"nombre": "toronja","estado": "crudo","cal": 32,"pr": 0.6,"gr": 0.2,"hc": 8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(196),"nombre": "uva blanca","estado": "crudo","cal": 74,"pr": 0.8,"gr": 1,"hc": 17})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(197),"nombre": "uva negra","estado": "crudo","cal": 110,"pr": 1.47,"gr": 0,"hc": 26})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(198),"nombre": "uva (jugo)","estado": "fresco","cal": 38,"pr": 2.5,"gr": 0.1,"hc": 8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(199),"nombre": "uva (jugo)","estado": "conserva","cal": 67,"pr": 1.8,"gr": 0,"hc": 18})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(200),"nombre": "albaricoque","estado": "seco","cal": 268,"pr": 5.3,"gr": 0.4,"hc": 67.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(201),"nombre": "almendras","estado": "seco","cal": 612,"pr": 19.7,"gr": 54.5,"hc": 17.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(202),"nombre": "avellana","estado": "seco","cal": 620,"pr": 15.5,"gr": 62.2,"hc": 15.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(203),"nombre": "cacahuete","estado": "seco","cal": 550,"pr": 26.1,"gr": 44.2,"hc": 20})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(204),"nombre": "cacahuete","estado": "tostado","cal": 610,"pr": 26.5,"gr": 48.1,"hc": 18.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(205),"nombre": "cacao","estado": "polvo","cal": 340,"pr": 26,"gr": 18.8,"hc": 38})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(206),"nombre": "castaña seca","estado": "cruda","cal": 350,"pr": 8.2,"gr": 3.5,"hc": 75.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(207),"nombre": "castaña tierna","estado": "cruda","cal": 188,"pr": 3.2,"gr": 2.5,"hc": 40})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(208),"nombre": "ciruela pasa","estado": "cruda","cal": 262,"pr": 2.4,"gr": 0.6,"hc": 72})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(209),"nombre": "coco","estado": "fresco","cal": 350,"pr": 3.8,"gr": 34.8,"hc": 14.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(210),"nombre": "coco","estado": "leche","cal": 25,"pr": 0.4,"gr": 0.2,"hc": 5.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(211),"nombre": "coco","estado": "seco","cal": 580,"pr": 4.7,"gr": 48,"hc": 41.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(212),"nombre": "datiles","estado": "secos","cal": 271,"pr": 2.2,"gr": 0.6,"hc": 72})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(213),"nombre": "higos","estado": "secos","cal": 280,"pr": 3.9,"gr": 1.3,"hc": 67.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(214),"nombre": "melocoton","estado": "secos","cal": 253,"pr": 3,"gr": 0.5,"hc": 63})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(215),"nombre": "nuez","estado": "secos","cal": 643,"pr": 17.8,"gr": 57.6,"hc": 17.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(216),"nombre": "piñones","estado": "secos","cal": 310,"pr": 26.4,"gr": 40,"hc": 29.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(217),"nombre": "uva","estado": "pasa","cal": 288,"pr": 3.1,"gr": 0.9,"hc": 69.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(218),"nombre": "helado","estado": "0","cal": 206,"pr": 3.9,"gr": 12,"hc": 21})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(219),"nombre": "leche de burra","estado": "fresca","cal": 42,"pr": 1.7,"gr": 1.5,"hc": 5.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(220),"nombre": "leche de cabra","estado": "fresca","cal": 68,"pr": 3.6,"gr": 4.4,"hc": 4.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(221),"nombre": "leche de mujer","estado": "fresca","cal": 68,"pr": 1.5,"gr": 3.8,"hc": 6.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(222),"nombre": "leche de oveja","estado": "fresca","cal": 86,"pr": 5.6,"gr": 5.5,"hc": 5.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(223),"nombre": "leche de vaca","estado": "fresca","cal": 68,"pr": 3.5,"gr": 3.8,"hc": 5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(224),"nombre": "leche de vaca","estado": "desnatada","cal": 36,"pr": 3.6,"gr": 0.1,"hc": 4.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(225),"nombre": "leche de vaca","estado": "entera","cal": 146,"pr": 7.86,"gr": 7.93,"hc": 11.03})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(226),"nombre": "leche vaca condens.","estado": "con azucar","cal": 348,"pr": 8.1,"gr": 8.9,"hc": 54.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(227),"nombre": "leche de vaca","estado": "total seca","cal": 510,"pr": 26.8,"gr": 27.9,"hc": 38.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(228),"nombre": "leche vaca cond. Desn.","estado": "seca","cal": 356,"pr": 36.8,"gr": 1.3,"hc": 53.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(229),"nombre": "leche de vaca","estado": "con cacao","cal": 100,"pr": 3.3,"gr": 4.3,"hc": 12})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(230),"nombre": "mantequilla","estado": "fresca","cal": 718,"pr": 0.68,"gr": 81.3,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(231),"nombre": "nata","estado": "fresca","cal": 362,"pr": 2.3,"gr": 38,"hc": 3.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(232),"nombre": "queso brugos","estado": "natural","cal": 190,"pr": 12.1,"gr": 14.6,"hc": 3.16})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(233),"nombre": "queso de cabra","estado": "","cal": 361,"pr": 23.52,"gr": 28.85,"hc": 1.87})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(234),"nombre": "queso emmertal","estado": "natural","cal": 397,"pr": 26.8,"gr": 30.5,"hc": 2.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(235),"nombre": "queso gervaia","estado": "natural","cal": 415,"pr": 19.7,"gr": 36,"hc": 2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(236),"nombre": "queso gorgonzola","estado": "natural","cal": 365,"pr": 24.5,"gr": 28,"hc": 1.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(237),"nombre": "queso graso","estado": "natural","cal": 270,"pr": 8,"gr": 25,"hc": 3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(238),"nombre": "queso gruyere","estado": "natural","cal": 420,"pr": 33,"gr": 32.2,"hc": 4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(239),"nombre": "queso magro","estado": "natural","cal": 200,"pr": 39,"gr": 1.8,"hc": 4.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(240),"nombre": "queso manchego","estado": "natural","cal": 400,"pr": 32.5,"gr": 32,"hc": 1.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(241),"nombre": "queso roquefort","estado": "natural","cal": 393,"pr": 23.4,"gr": 33.6,"hc": 2.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(242),"nombre": "queso semigraso","estado": "natural","cal": 253,"pr": 36.2,"gr": 9.9,"hc": 3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(243),"nombre": "queso villalon","estado": "natural","cal": 450,"pr": 17.5,"gr": 46,"hc": 1.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(244),"nombre": "Yogur griego","estado": "","cal": 129,"pr": 3.9,"gr": 10.8,"hc": 3.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(245),"nombre": "yogur","estado": "natural","cal": 62,"pr": 3.8,"gr": 3.5,"hc": 4.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(246),"nombre": "Huevo entero","estado": "Crudo","cal": 155,"pr": 13.6,"gr": 10.9,"hc": 0.55})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(247),"nombre": "Huevo Clara","estado": "Crudo","cal": 53,"pr": 10.4,"gr": 0.3,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(248),"nombre": "Huevo Yema","estado": "Crudo","cal": 352,"pr": 16.4,"gr": 30.1,"hc": 0.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(249),"nombre": "Huevo","estado": "Escalfado","cal": 154,"pr": 12.2,"gr": 11.3,"hc": 0.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(250),"nombre": "Huevo","estado": "Frito","cal": 220,"pr": 13.6,"gr": 17.5,"hc": 2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(251),"nombre": "Huevo","estado": "Hervido","cal": 155,"pr": 12.1,"gr": 11.6,"hc": 0.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(252),"nombre": "Huevo","estado": "Revuelto","cal": 250,"pr": 11.7,"gr": 18.3,"hc": 1.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(253),"nombre": "Huevo","estado": "seco","cal": 567,"pr": 44.1,"gr": 43,"hc": 2.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(254),"nombre": "Huevo","estado": "Tortilla","cal": 258,"pr": 9.1,"gr": 26.3,"hc": 4.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(255),"nombre": "Huevo de pata","estado": "Crudo","cal": 141,"pr": 9.1,"gr": 10.2,"hc": 2.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(256),"nombre": "Huevo de Pava","estado": "Crudo","cal": 162,"pr": 13.2,"gr": 1,"hc": 11.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(257),"nombre": "Azucar","estado": "refinado","cal": 401,"pr": 0,"gr": 0,"hc": 99.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(258),"nombre": "Azucar","estado": "sin refinar","cal": 378,"pr": 1.4,"gr": 0,"hc": 93.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(259),"nombre": "Azucar moreno","estado": "","cal": 377,"pr": 0,"gr": 0,"hc": 97.33})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(260),"nombre": "Caldo en Cubitos","estado": "0","cal": 190,"pr": 11,"gr": 1.4,"hc": 47})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(261),"nombre": "Caramelos ","estado": "0","cal": 397,"pr": 2.4,"gr": 11.6,"hc": 79.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(262),"nombre": "Confituras","estado": "0","cal": 292,"pr": 0.6,"gr": 2.1,"hc": 69.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(263),"nombre": "Chocolate","estado": "amargo","cal": 561,"pr": 5.7,"gr": 53.3,"hc": 38})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(264),"nombre": "Chocolate","estado": "lacteado","cal": 558,"pr": 7.4,"gr": 31.3,"hc": 53})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(265),"nombre": "Jaleas","estado": "0","cal": 270,"pr": 3.1,"gr": 0.3,"hc": 67})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(266),"nombre": "Levadura","estado": "prensada","cal": 96,"pr": 13.1,"gr": 0.28,"hc": 12.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(267),"nombre": "Levadura","estado": "seca","cal": 276,"pr": 38.9,"gr": 1.8,"hc": 39.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(268),"nombre": "Malta (extracto)","estado": "seco","cal": 300,"pr": 5.2,"gr": 0,"hc": 84.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(269),"nombre": "Melaza","estado": "0","cal": 242,"pr": 2.4,"gr": 0,"hc": 69.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(270),"nombre": "Miel de Abeja","estado": "0","cal": 328,"pr": 0.4,"gr": 0,"hc": 81})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(271),"nombre": "Aceite de oliva","estado": "0","cal": 119,"pr": 0,"gr": 13.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(272),"nombre": "Aceite de girasol","estado": "","cal": 884,"pr": 0,"gr": 100,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(273),"nombre": "Mahonesa","estado": "0","cal": 720,"pr": 1.5,"gr": 78,"hc": 8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(274),"nombre": "Manteca Cerdo grasa","estado": "0","cal": 893,"pr": 0.5,"gr": 99.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(275),"nombre": "Margarina","estado": "0","cal": 732,"pr": 0.5,"gr": 88.5,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(276),"nombre": "Abadejo","estado": "fresco","cal": 58,"pr": 13.6,"gr": 0.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(277),"nombre": "abadejo (seco)","estado": "salado","cal": 361,"pr": 81.5,"gr": 2.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(278),"nombre": "abadejo","estado": "cocido","cal": 107,"pr": 23.7,"gr": 1.1,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(279),"nombre": "abadejo","estado": "frito","cal": 170,"pr": 17.6,"gr": 9.5,"hc": 6.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(280),"nombre": "almeja","estado": "fresco","cal": 81,"pr": 13.5,"gr": 1.6,"hc": 8.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(281),"nombre": "almeja","estado": "cocido","cal": 68,"pr": 12.1,"gr": 2.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(282),"nombre": "anchoas","estado": "fresco","cal": 138,"pr": 21.4,"gr": 5.8,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(283),"nombre": "anchoas","estado": "conserva","cal": 185,"pr": 18.8,"gr": 11.2,"hc": 1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(284),"nombre": "anguila de rio","estado": "fresco","cal": 142,"pr": 18.8,"gr": 13.6,"hc": 3.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(285),"nombre": "anguila de rio","estado": "cocida","cal": 232,"pr": 13.1,"gr": 17.3,"hc": 3.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(286),"nombre": "arenque","estado": "fresco","cal": 120,"pr": 16.8,"gr": 8.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(287),"nombre": "arenque","estado": "frito","cal": 212,"pr": 21.9,"gr": 13.7,"hc": 1.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(288),"nombre": "atun","estado": "fresco","cal": 148,"pr": 18.9,"gr": 9.1,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(289),"nombre": "atun","estado": "conserva","cal": 261,"pr": 33.2,"gr": 14.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(290),"nombre": "bacalao","estado": "fresco","cal": 64,"pr": 14.3,"gr": 0.5,"hc": 6.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(291),"nombre": "bacalao seco","estado": "salado","cal": 230,"pr": 38.7,"gr": 7.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(292),"nombre": "balalao","estado": "cocido","cal": 94,"pr": 19.2,"gr": 3.1,"hc": 5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(293),"nombre": "bacalao","estado": "frito","cal": 181,"pr": 21.7,"gr": 9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(294),"nombre": "barbo","estado": "fresco","cal": 95,"pr": 15.2,"gr": 4.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(295),"nombre": "barbo","estado": "cocido","cal": 120,"pr": 19.3,"gr": 5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(296),"nombre": "barbo","estado": "frito","cal": 153,"pr": 18.8,"gr": 10.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(297),"nombre": "bonito","estado": "fresco","cal": 147,"pr": 26.7,"gr": 4.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(298),"nombre": "boqueron","estado": "fresco","cal": 110,"pr": 21.2,"gr": 3.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(299),"nombre": "boqueron","estado": "conserva","cal": 177,"pr": 22,"gr": 10.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(300),"nombre": "breca","estado": "fresca","cal": 75,"pr": 17,"gr": 0.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(301),"nombre": "breca","estado": "frita ","cal": 146,"pr": 19.6,"gr": 8.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(302),"nombre": "calamar","estado": "fresco","cal": 62,"pr": 8.7,"gr": 3.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(303),"nombre": "calamar","estado": "cocido","cal": 73,"pr": 9.4,"gr": 4.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(304),"nombre": "calamar","estado": "frito","cal": 118,"pr": 10.1,"gr": 9.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(305),"nombre": "camaron","estado": "fresco ","cal": 121,"pr": 26.5,"gr": 1.6,"hc": 4.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(306),"nombre": "camaron","estado": "cocido","cal": 128,"pr": 25.2,"gr": 1.8,"hc": 0.45})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(307),"nombre": "cangrejo","estado": "fresco","cal": 89,"pr": 14.2,"gr": 2.7,"hc": 1.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(308),"nombre": "cangrejo","estado": "cocido","cal": 103,"pr": 14,"gr": 4.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(309),"nombre": "carpa","estado": "fresco","cal": 97,"pr": 19.4,"gr": 1.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(310),"nombre": "carpa","estado": "cocido","cal": 92,"pr": 19.2,"gr": 1.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(311),"nombre": "carpa","estado": "frita ","cal": 115,"pr": 20.1,"gr": 4.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(312),"nombre": "caviar","estado": "conserva","cal": 276,"pr": 32,"gr": 16,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(313),"nombre": "centollo","estado": "fresco","cal": 64,"pr": 13.6,"gr": 2.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(314),"nombre": "centollo","estado": "cocido","cal": 75,"pr": 14.8,"gr": 2.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(315),"nombre": "congrio","estado": "fresco","cal": 98,"pr": 15.7,"gr": 4.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(316),"nombre": "congrio","estado": "cocido","cal": 109,"pr": 20.8,"gr": 3.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(317),"nombre": "congrio","estado": "frito","cal": 246,"pr": 17.3,"gr": 19,"hc": 6.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(318),"nombre": "chirla","estado": "fresco","cal": 79,"pr": 12.8,"gr": 1.4,"hc": 3.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(319),"nombre": "dorada","estado": "fresco","cal": 83,"pr": 18.6,"gr": 1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(320),"nombre": "dorada","estado": "cocido","cal": 91,"pr": 19.9,"gr": 1.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(321),"nombre": "faneca","estado": "fresca","cal": 76,"pr": 18.8,"gr": 0.14,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(322),"nombre": "faneca","estado": "cocida","cal": 83,"pr": 20.1,"gr": 0.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(323),"nombre": "faneca","estado": "frita ","cal": 124,"pr": 19,"gr": 6.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(324),"nombre": "gallo","estado": "fresco","cal": 79,"pr": 19,"gr": 1.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(325),"nombre": "gallo","estado": "cocido","cal": 97,"pr": 20.6,"gr": 1.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(326),"nombre": "gallo","estado": "frito","cal": 122,"pr": 20.6,"gr": 5.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(327),"nombre": "gambas","estado": "fresco","cal": 96,"pr": 20.1,"gr": 2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(328),"nombre": "gambas","estado": "cocidas","cal": 107,"pr": 22.3,"gr": 2.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(329),"nombre": "hipoglomo (halibut(","estado": "fresco","cal": 126,"pr": 18.9,"gr": 4.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(330),"nombre": "langosta","estado": "frseca","cal": 90,"pr": 17.5,"gr": 1.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(331),"nombre": "langosta","estado": "cocida","cal": 106,"pr": 8.2,"gr": 3.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(332),"nombre": "langostino","estado": "fresco","cal": 240,"pr": 45.7,"gr": 10.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(333),"nombre": "langostino","estado": "cocido","cal": 124,"pr": 39.2,"gr": 8.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(334),"nombre": "lenguado","estado": "fresco","cal": 74,"pr": 17.3,"gr": 0.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(335),"nombre": "lenguado","estado": "cocido","cal": 93,"pr": 19.4,"gr": 1.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(336),"nombre": "lenguado","estado": "frito","cal": 221,"pr": 20.1,"gr": 15.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(337),"nombre": "lija","estado": "cocida","cal": 98,"pr": 21.8,"gr": 0.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(338),"nombre": "lija","estado": "frita ","cal": 169,"pr": 17,"gr": 8.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(339),"nombre": "lubina","estado": "fresca","cal": 97,"pr": 15.4,"gr": 4.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(340),"nombre": "lubina","estado": "cocida","cal": 123,"pr": 19.5,"gr": 5.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(341),"nombre": "mecarel","estado": "fresca","cal": 160,"pr": 18.9,"gr": 9.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(342),"nombre": "mecarel","estado": "frito","cal": 185,"pr": 19.8,"gr": 11.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(343),"nombre": "mejillon","estado": "frsco","cal": 62,"pr": 9.8,"gr": 1.6,"hc": 2.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(344),"nombre": "mejillon","estado": "cocido","cal": 87,"pr": 16.8,"gr": 2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(345),"nombre": "merluza","estado": "fresco","cal": 87,"pr": 16.7,"gr": 2.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(346),"nombre": "merluza","estado": "cocido","cal": 104,"pr": 18.3,"gr": 3.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(347),"nombre": "merluza","estado": "frita ","cal": 170,"pr": 18.3,"gr": 9.3,"hc": 6.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(348),"nombre": "mero","estado": "fresco","cal": 86,"pr": 19.2,"gr": 1.04,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(349),"nombre": "mero","estado": "cocido","cal": 107,"pr": 20.4,"gr": 3.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(350),"nombre": "mujol","estado": "fresco","cal": 68,"pr": 17.8,"gr": 1.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(351),"nombre": "mujol","estado": "cocido","cal": 123,"pr": 21.6,"gr": 4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(352),"nombre": "navajas","estado": "fresco","cal": 118,"pr": 26.7,"gr": 1.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(353),"nombre": "ostras","estado": "fresco","cal": 53,"pr": 9.6,"gr": 1.5,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(354),"nombre": "ostras","estado": "cocido","cal": 87,"pr": 5.3,"gr": 5.4,"hc": 5.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(355),"nombre": "percas","estado": "fresco","cal": 83,"pr": 16.7,"gr": 1.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(356),"nombre": "percas","estado": "cocido","cal": 92,"pr": 18.4,"gr": 2.2,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(357),"nombre": "percebes","estado": "cocido","cal": 75,"pr": 19.2,"gr": 1.9,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(358),"nombre": "pescadilla","estado": "fresco","cal": 70,"pr": 16.4,"gr": 0.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(359),"nombre": "pescadilla","estado": "cocido","cal": 95,"pr": 20.9,"gr": 0.8,"hc": 1.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(360),"nombre": "pescadilla","estado": "frito","cal": 183,"pr": 19.6,"gr": 10.7,"hc": 2.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(361),"nombre": "platija","estado": "fresco","cal": 80,"pr": 15.8,"gr": 1.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(362),"nombre": "platija","estado": "cocido","cal": 90,"pr": 16.9,"gr": 1.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(363),"nombre": "platija","estado": "frita ","cal": 219,"pr": 15.4,"gr": 13,"hc": 9.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(364),"nombre": "rana (ancas)","estado": "fresco","cal": 72,"pr": 16.3,"gr": 0.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(365),"nombre": "rana (ancas)","estado": "frita ","cal": 283,"pr": 22,"gr": 7.9,"hc": 8.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(366),"nombre": "rape","estado": "fresco","cal": 73,"pr": 15.8,"gr": 1.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(367),"nombre": "rape","estado": "cocido","cal": 82,"pr": 16.5,"gr": 2.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(368),"nombre": "raya","estado": "frito","cal": 242,"pr": 15,"gr": 16.4,"hc": 7.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(369),"nombre": "rodaballo","estado": "fresco","cal": 81,"pr": 18.1,"gr": 1.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(370),"nombre": "rodaballo","estado": "cocido","cal": 117,"pr": 26.2,"gr": 1.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(371),"nombre": "salmon","estado": "fresco","cal": 145,"pr": 21.5,"gr": 7.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(372),"nombre": "salmon","estado": "cocido","cal": 195,"pr": 20.8,"gr": 10.6,"hc": 3.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(373),"nombre": "salmon","estado": "conserva","cal": 155,"pr": 20.3,"gr": 8.2,"hc": 0.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(374),"nombre": "salmonete","estado": "fresco","cal": 69,"pr": 13.5,"gr": 1.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(375),"nombre": "salmonete","estado": "cocido","cal": 118,"pr": 21.4,"gr": 4.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(376),"nombre": "salmonete","estado": "frito","cal": 164,"pr": 17.6,"gr": 10.5,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(377),"nombre": "sardina","estado": "fresco","cal": 141,"pr": 21.8,"gr": 6.3,"hc": 1.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(378),"nombre": "sardina","estado": "cocido","cal": 225,"pr": 24.9,"gr": 14,"hc": 1.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(379),"nombre": "sardina","estado": "frita ","cal": 347,"pr": 19.6,"gr": 33.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(380),"nombre": "sardina","estado": "coserva ","cal": 209,"pr": 19.8,"gr": 14.5,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(381),"nombre": "sollo","estado": "fresco","cal": 80,"pr": 17.1,"gr": 1.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(382),"nombre": "sollo","estado": "cocido","cal": 122,"pr": 23.2,"gr": 4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(383),"nombre": "tenca","estado": "fresco","cal": 55,"pr": 8.2,"gr": 2.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(384),"nombre": "tenca","estado": "cocido","cal": 88,"pr": 16,"gr": 3.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(385),"nombre": "trucha","estado": "fresco","cal": 96,"pr": 19.2,"gr": 2.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(386),"nombre": "trucha","estado": "cocido","cal": 133,"pr": 22.3,"gr": 3.8,"hc": 1.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(387),"nombre": "trucha","estado": "frita ","cal": 188,"pr": 26,"gr": 10.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(388),"nombre": "vieira","estado": "fresco","cal": 73,"pr": 14.8,"gr": 1.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(389),"nombre": "volador","estado": "fresco","cal": 87,"pr": 15.8,"gr": 3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(390),"nombre": "volador","estado": "cocido","cal": 130,"pr": 21.6,"gr": 5.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(391),"nombre": "Carne de vacuno","estado": "picada","cal": 182,"pr": 17,"gr": 12,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(392),"nombre": "Caballo (Carne)","estado": "cruda","cal": 112,"pr": 19,"gr": 4,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(393),"nombre": "Cabra (carne)","estado": "cruda","cal": 127,"pr": 19.6,"gr": 4.3,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(394),"nombre": "Cabrito (carne)","estado": "cruda","cal": 40,"pr": 7.2,"gr": 1.6,"hc": 0.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(395),"nombre": "Carnero (carne)","estado": "cruda","cal": 210,"pr": 17.5,"gr": 16,"hc": 0.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(396),"nombre": "Corazon","estado": "crudo","cal": 117,"pr": 16.8,"gr": 4.9,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(397),"nombre": "costillas magras","estado": "crudo","cal": 215,"pr": 14.5,"gr": 17,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(398),"nombre": "costillas magras","estado": "estofado","cal": 306,"pr": 22.1,"gr": 24.2,"hc": 2.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(399),"nombre": "costillas magras","estado": "frito","cal": 308,"pr": 21.5,"gr": 26.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(400),"nombre": "costillas semimagr.","estado": "estofado","cal": 505,"pr": 18.6,"gr": 50.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(401),"nombre": "costillas semimagr.","estado": "frito","cal": 560,"pr": 15.2,"gr": 62,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(402),"nombre": "higado","estado": "crudo","cal": 134,"pr": 19.4,"gr": 4.9,"hc": 1.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(403),"nombre": "higado","estado": "frito","cal": 236,"pr": 22.7,"gr": 10.8,"hc": 9.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(404),"nombre": "Jamon","estado": "crudo","cal": 262,"pr": 15.8,"gr": 18.7,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(405),"nombre": "Jamon","estado": "cocido","cal": 354,"pr": 20.3,"gr": 32.1,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(406),"nombre": "jamon York","estado": "crudo","cal": 454,"pr": 17.2,"gr": 43,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(407),"nombre": "jamon York","estado": "cocido","cal": 435,"pr": 16.2,"gr": 39.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(408),"nombre": "lomo graso","estado": "asado","cal": 412,"pr": 23.7,"gr": 35.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(409),"nombre": "lomo graso","estado": "estofado","cal": 404,"pr": 18.6,"gr": 41.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(410),"nombre": "lomo graso","estado": "frito","cal": 489,"pr": 16.1,"gr": 53.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(411),"nombre": "lomo magro","estado": "asado","cal": 271,"pr": 26.1,"gr": 18.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(412),"nombre": "lomo magro","estado": "estofado","cal": 285,"pr": 20.3,"gr": 23.2,"hc": 1.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(413),"nombre": "lomo magro","estado": "frito","cal": 316,"pr": 19.6,"gr": 28.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(414),"nombre": "manteca","estado": "crudo","cal": 877,"pr": 0.8,"gr": 98,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(415),"nombre": "pierna","estado": "asado","cal": 317,"pr": 24.6,"gr": 23.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(416),"nombre": "promedio","estado": "0","cal": 736,"pr": 3.9,"gr": 80,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(417),"nombre": "riñon","estado": "crudo","cal": 105,"pr": 15.2,"gr": 4.3,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(418),"nombre": "tocino","estado": "salado","cal": 763,"pr": 6.6,"gr": 80.2,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(419),"nombre": "Corazon","estado": "asado","cal": 239,"pr": 25,"gr": 14.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(420),"nombre": "Costillas grasas","estado": "crudo","cal": 312,"pr": 14.9,"gr": 29.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(421),"nombre": "Costillas grasas","estado": "estofado","cal": 424,"pr": 20.1,"gr": 40.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(422),"nombre": "Costillas grasas","estado": "asado","cal": 396,"pr": 21.7,"gr": 37.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(423),"nombre": "Costillas grasas","estado": "frito","cal": 480,"pr": 15.4,"gr": 52.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(424),"nombre": "Costillas Magras","estado": "crudo","cal": 158,"pr": 19.3,"gr": 8.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(425),"nombre": "Costillas Magras","estado": "estofado","cal": 235,"pr": 26.9,"gr": 14.9,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(426),"nombre": "Costillas Magras","estado": "asado","cal": 195,"pr": 23.3,"gr": 11.7,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(427),"nombre": "Costillas Magras","estado": "frito","cal": 305,"pr": 24.8,"gr": 23.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(428),"nombre": "cuello","estado": "estofado","cal": 326,"pr": 24.2,"gr": 24.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(429),"nombre": "higado","estado": "crudo","cal": 131,"pr": 20,"gr": 3.8,"hc": 2.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(430),"nombre": "higado","estado": "cocido","cal": 232,"pr": 24.8,"gr": 8.5,"hc": 10.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(431),"nombre": "lengua","estado": "estofado","cal": 297,"pr": 18,"gr": 24,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(432),"nombre": "paletilla","estado": "cocido","cal": 335,"pr": 23.5,"gr": 24.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(433),"nombre": "pierna","estado": "crudo","cal": 235,"pr": 18,"gr": 17.5,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(434),"nombre": "pierna","estado": "estofado","cal": 262,"pr": 20.3,"gr": 17.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(435),"nombre": "pierna","estado": "asado","cal": 260,"pr": 22,"gr": 19,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(436),"nombre": "riñon","estado": "crudo","cal": 99,"pr": 16.6,"gr": 3,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(437),"nombre": "riñon","estado": "frito","cal": 192,"pr": 28,"gr": 9.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(438),"nombre": "sesos","estado": "cocido","cal": 103,"pr": 11.7,"gr": 6.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(439),"nombre": "Carne","estado": "cruda","cal": 134,"pr": 19.2,"gr": 6.6,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(440),"nombre": "Carne","estado": "cocida","cal": 165,"pr": 23.3,"gr": 9.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(441),"nombre": "corazon","estado": "crudo ","cal": 130,"pr": 15.4,"gr": 7.1,"hc": 1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(442),"nombre": "costillas","estado": "crudo ","cal": 135,"pr": 19.5,"gr": 7.5,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(443),"nombre": "costillas","estado": "asado","cal": 232,"pr": 30.5,"gr": 12.6,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(444),"nombre": "costillas","estado": "frito","cal": 296,"pr": 27.5,"gr": 20.1,"hc": 4.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(445),"nombre": "filete","estado": "crudo ","cal": 108,"pr": 20.1,"gr": 2.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(446),"nombre": "filete","estado": "asado","cal": 232,"pr": 30.5,"gr": 11.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(447),"nombre": "higado","estado": "crudo ","cal": 134,"pr": 18.7,"gr": 5.2,"hc": 3.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(448),"nombre": "higado","estado": "cocido","cal": 167,"pr": 20.7,"gr": 7,"hc": 4.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(449),"nombre": "higado","estado": "frito","cal": 237,"pr": 26.5,"gr": 13.3,"hc": 3.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(450),"nombre": "lechecillas","estado": "crudo ","cal": 103,"pr": 17.6,"gr": 3.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(451),"nombre": "lechecillas","estado": "estofado","cal": 162,"pr": 22.7,"gr": 8.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(452),"nombre": "lengua","estado": "estofado","cal": 190,"pr": 15.9,"gr": 14.8,"hc": 0.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(453),"nombre": "promedio","estado": "0","cal": 184,"pr": 19.1,"gr": 12,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(454),"nombre": "riñon","estado": "cocido","cal": 102,"pr": 15.4,"gr": 4.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(455),"nombre": "riñon","estado": "frito","cal": 182,"pr": 14.8,"gr": 15.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(456),"nombre": "sesos","estado": "cocido","cal": 115,"pr": 10.3,"gr": 8.3,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(457),"nombre": "solomillo","estado": "crudo ","cal": 93,"pr": 19.3,"gr": 1.6,"hc": 2.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(458),"nombre": "solomillo","estado": "asado","cal": 192,"pr": 28.7,"gr": 8.5,"hc": 3.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(459),"nombre": "solomillo","estado": "frito","cal": 268,"pr": 23.8,"gr": 20.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(460),"nombre": "tripas","estado": "cocido","cal": 99,"pr": 18,"gr": 3.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(461),"nombre": "Bistec","estado": "crudo","cal": 177,"pr": 19.2,"gr": 10.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(462),"nombre": "Bistec","estado": "frito","cal": 273,"pr": 20.4,"gr": 20.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(463),"nombre": "Carne","estado": "crudo","cal": 140,"pr": 18.2,"gr": 7.5,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(464),"nombre": "Carne","estado": "congelado","cal": 142,"pr": 20.3,"gr": 7.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(465),"nombre": "Carne semigrasa","estado": "crudo","cal": 246,"pr": 17.1,"gr": 16.2,"hc": 0.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(466),"nombre": "Carne semigrasa","estado": "asado","cal": 355,"pr": 18.1,"gr": 25.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(467),"nombre": "Carne semigrasa","estado": "cocido","cal": 210,"pr": 32.5,"gr": 8.2,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(468),"nombre": "Corazon","estado": "crudo","cal": 112,"pr": 17.2,"gr": 4.6,"hc": 0.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(469),"nombre": "Costilla","estado": "cocido","cal": 280,"pr": 26.3,"gr": 5.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(470),"nombre": "Falda","estado": "cocido","cal": 413,"pr": 18.1,"gr": 38,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(471),"nombre": "Higado","estado": "crudo","cal": 130,"pr": 20,"gr": 3.5,"hc": 3.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(472),"nombre": "Higado","estado": "cocido","cal": 148,"pr": 23,"gr": 7.8,"hc": 4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(473),"nombre": "Higado","estado": "frito","cal": 229,"pr": 26,"gr": 9.1,"hc": 9.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(474),"nombre": "Lengua","estado": "crudo","cal": 210,"pr": 15.8,"gr": 16.3,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(475),"nombre": "Lengua","estado": "cocido","cal": 239,"pr": 19.3,"gr": 15.3,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(476),"nombre": "Promedio","estado": "cocido","cal": 268,"pr": 17.5,"gr": 22,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(477),"nombre": "Riñon","estado": "crudo","cal": 122,"pr": 16.2,"gr": 6,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(478),"nombre": "Riñon","estado": "cocido","cal": 165,"pr": 27,"gr": 5.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(479),"nombre": "sangre","estado": "crudo","cal": 77,"pr": 18.1,"gr": 0.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(480),"nombre": "sesos","estado": "crudo","cal": 120,"pr": 10,"gr": 8.5,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(481),"nombre": "sesos","estado": "cocidos","cal": 126,"pr": 10.4,"gr": 9.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(482),"nombre": "solomillo","estado": "crudo","cal": 120,"pr": 21,"gr": 3.9,"hc": 0.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(483),"nombre": "solomillo","estado": "asado","cal": 214,"pr": 25.3,"gr": 12.1,"hc": 1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(484),"nombre": "solomillo","estado": "cocido","cal": 172,"pr": 22,"gr": 9.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(485),"nombre": "solomillo","estado": "frito","cal": 279,"pr": 19.1,"gr": 23.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(486),"nombre": "tripas","estado": "crudo","cal": 96,"pr": 17,"gr": 2,"hc": 0.15})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(487),"nombre": "Butifarra","estado": "Natural","cal": 150,"pr": 9.8,"gr": 13.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(488),"nombre": "Chorizo","estado": "natural","cal": 614,"pr": 13.6,"gr": 70.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(489),"nombre": "Chorizo","estado": "frito","cal": 360,"pr": 19.6,"gr": 60.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(490),"nombre": "Morcilla","estado": "natural","cal": 258,"pr": 5.3,"gr": 22.5,"hc": 14.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(491),"nombre": "Morcilla","estado": "cocido","cal": 335,"pr": 13.7,"gr": 29.1,"hc": 15.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(492),"nombre": "Morcilla","estado": "frita","cal": 453,"pr": 13.9,"gr": 42.9,"hc": 15.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(493),"nombre": "salchicha de cerdo","estado": "natural","cal": 390,"pr": 9.8,"gr": 36.3,"hc": 9.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(494),"nombre": "salchicha de cerdo","estado": "cocida","cal": 360,"pr": 16.5,"gr": 28.6,"hc": 7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(495),"nombre": "salchicha de cerdo","estado": "frita","cal": 326,"pr": 13.4,"gr": 29.3,"hc": 12.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(496),"nombre": "salchicha de vaca","estado": "natural","cal": 140,"pr": 9.1,"gr": 8.3,"hc": 10.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(497),"nombre": "salchicha de vaca","estado": "cocida","cal": 210,"pr": 15.6,"gr": 12.1,"hc": 13.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(498),"nombre": "salchicha de vaca","estado": "frita","cal": 264,"pr": 13.8,"gr": 18.4,"hc": 15.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(499),"nombre": "salchicha de Frankfurt","estado": "natural","cal": 248,"pr": 14,"gr": 20,"hc": 2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(500),"nombre": "Salchichon","estado": "Natural","cal": 430,"pr": 20.3,"gr": 36.7,"hc": 0.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(501),"nombre": "Capon","estado": "crudo","cal": 158,"pr": 18.7,"gr": 9.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(502),"nombre": "capon","estado": "asado","cal": 238,"pr": 22.7,"gr": 18.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(503),"nombre": "codoriz","estado": "crudo","cal": 175,"pr": 16.7,"gr": 11.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(504),"nombre": "codoriz","estado": "estofado","cal": 230,"pr": 18.5,"gr": 19.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(505),"nombre": "codoriz","estado": "asado","cal": 240,"pr": 19.3,"gr": 20.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(506),"nombre": "Faisan","estado": "crudo","cal": 138,"pr": 22,"gr": 5.3,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(507),"nombre": "Faisan","estado": "estofado","cal": 250,"pr": 28.6,"gr": 17.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(508),"nombre": "Faisan","estado": "asado","cal": 256,"pr": 30.8,"gr": 14.3,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(509),"nombre": "Gallina Joven","estado": "crudo","cal": 112,"pr": 21,"gr": 2.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(510),"nombre": "Gallina Vieja","estado": "crudo","cal": 302,"pr": 17,"gr": 24,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(511),"nombre": "Gallina Vieja","estado": "asado","cal": 194,"pr": 30.1,"gr": 7.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(512),"nombre": "Ganso","estado": "crudo","cal": 320,"pr": 15.6,"gr": 26.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(513),"nombre": "Ganso","estado": "asado","cal": 322,"pr": 24,"gr": 26.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(514),"nombre": "Paloma","estado": "crudo","cal": 135,"pr": 20.4,"gr": 12,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(515),"nombre": "Paloma","estado": "estofado","cal": 212,"pr": 24.5,"gr": 13.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(516),"nombre": "Paloma","estado": "asado","cal": 212,"pr": 26.9,"gr": 10.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(517),"nombre": "Pato","estado": "crudo","cal": 232,"pr": 17.4,"gr": 17.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(518),"nombre": "Pato","estado": "asado","cal": 196,"pr": 22.8,"gr": 23.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(519),"nombre": "Pavo","estado": "crudo","cal": 184,"pr": 18.5,"gr": 19,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(520),"nombre": "Pavo","estado": "asado","cal": 200,"pr": 27.1,"gr": 12.1,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(521),"nombre": "Perdiz","estado": "crudo","cal": 120,"pr": 22.2,"gr": 3.8,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(522),"nombre": "Perdiz","estado": "asado","cal": 217,"pr": 35.2,"gr": 8.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(523),"nombre": "Perdiz","estado": "estofado","cal": 218,"pr": 36.1,"gr": 9.6,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(524),"nombre": "Pintada","estado": "crudo","cal": 210,"pr": 32.5,"gr": 8.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(525),"nombre": "Pollo","estado": "crudo","cal": 117,"pr": 18,"gr": 3.1,"hc": 3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(526),"nombre": "Pollo","estado": "cocido","cal": 186,"pr": 25.8,"gr": 9.1,"hc": 0.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(527),"nombre": "Pollo (pechuga)","estado": "","cal": 195,"pr": 29.55,"gr": 7.72,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(528),"nombre": "Pollo (corazon)","estado": "crudo","cal": 156,"pr": 19.7,"gr": 6.9,"hc": 1.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(529),"nombre": "Pollo (higado)","estado": "crudo","cal": 136,"pr": 20.8,"gr": 4,"hc": 2.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(530),"nombre": "Ciervo","estado": "Crudo","cal": 116,"pr": 18.2,"gr": 4,"hc": 0.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(531),"nombre": "Ciervo","estado": "Asado","cal": 180,"pr": 30.2,"gr": 4.4,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(532),"nombre": "Cobaya","estado": "Crudo","cal": 86,"pr": 19.2,"gr": 1.7,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(533),"nombre": "Conejo","estado": "Crudo","cal": 128,"pr": 16.5,"gr": 6.6,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(534),"nombre": "Conejo","estado": "Asado","cal": 218,"pr": 29.1,"gr": 12.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(535),"nombre": "Conejo","estado": "Estofado","cal": 181,"pr": 27.6,"gr": 7.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(536),"nombre": "Corzo","estado": "Crudo","cal": 116,"pr": 18.3,"gr": 4,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(537),"nombre": "Corzo","estado": "Asado","cal": 168,"pr": 29,"gr": 5.7,"hc": 2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(538),"nombre": "Jabali","estado": "Crudo","cal": 158,"pr": 16,"gr": 11.2,"hc": 0.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(539),"nombre": "Jabali","estado": "Asado","cal": 460,"pr": 29.5,"gr": 43.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(540),"nombre": "Liebre","estado": "Crudo","cal": 128,"pr": 19.8,"gr": 5.4,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(541),"nombre": "Liebre","estado": "Asado","cal": 219,"pr": 36.2,"gr": 7.3,"hc": 0.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(542),"nombre": "Liebre","estado": "Estofado","cal": 209,"pr": 29.4,"gr": 10.2,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(543),"nombre": "Vino blanco","estado": "","cal": 83,"pr": 0.07,"gr": 0,"hc": 2.58})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(544),"nombre": "Agua","estado": "","cal": 0,"pr": 0,"gr": 0,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(545),"nombre": "Vino de jerez","estado": "","cal": 127,"pr": 0.2,"gr": 0,"hc": 10})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(546),"nombre": "Pimiento verde","estado": "","cal": 20,"pr": 0.86,"gr": 0.17,"hc": 4.64})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(547),"nombre": "Sal","estado": "","cal": 0,"pr": 0.1,"gr": 0,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(548),"nombre": "Laurel","estado": "","cal": 353,"pr": 7.61,"gr": 8.36,"hc": 46.67})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(549),"nombre": "Tomillo","estado": "","cal": 336,"pr": 9.1,"gr": 7.4,"hc": 57.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(550),"nombre": "Pimenton","estado": "","cal": 29,"pr": 0.8,"gr": 0.41,"hc": 6.68})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(551),"nombre": "Azafran","estado": "","cal": 310,"pr": 11.43,"gr": 5.85,"hc": 65.37})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(552),"nombre": "Clavo","estado": "","cal": 323,"pr": 6,"gr": 5.4,"hc": 61.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(553),"nombre": "Vinagre","estado": "","cal": 18,"pr": 0,"gr": 0,"hc": 0.04})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(554),"nombre": "Caldo de verduras","estado": "","cal": 5,"pr": 0.2,"gr": 0.1,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(555),"nombre": "Alubia blanca","estado": "cocida","cal": 83,"pr": 5.8,"gr": 0.4,"hc": 10.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(556),"nombre": "Aceite de oliva virgen extra","estado": "","cal": 119,"pr": 0,"gr": 13.5,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(557),"nombre": "Caldo de carne","estado": "","cal": 7,"pr": 0.84,"gr": 0.19,"hc": 0.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(558),"nombre": "Panceta","estado": "","cal": 398,"pr": 16.26,"gr": 36.34,"hc": 0.15})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(559),"nombre": "Secreto ibérico","estado": "","cal": 225,"pr": 22.12,"gr": 14.45,"hc": 0.03})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(560),"nombre": "Caldo de pollo","estado": "","cal": 12,"pr": 0.95,"gr": 0.29,"hc": 1.51})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(561),"nombre": "Plátano verde","estado": "","cal": 85,"pr": 1.04,"gr": 0.31,"hc": 21.75})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(562),"nombre": "Comino","estado": "","cal": 8,"pr": 0.37,"gr": 0.47,"hc": 0.93})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(563),"nombre": "Bouquet garni","estado": "","cal": 59,"pr": 0,"gr": 5,"hc": 3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(564),"nombre": "Arroz basmati","estado": "","cal": 335,"pr": 9,"gr": 0.6,"hc": 78})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(565),"nombre": "Chile rojo","estado": "","cal": 19,"pr": 1,"gr": 0,"hc": 4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(566),"nombre": "Jengibre","estado": "","cal": 2,"pr": 0.04,"gr": 0.02,"hc": 0.36})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(567),"nombre": "Ajete","estado": "","cal": 29,"pr": 2.1,"gr": 0.23,"hc": 3.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(568),"nombre": "Queso parmesano","estado": "","cal": 22,"pr": 1.92,"gr": 1.43,"hc": 0.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(569),"nombre": "Burrata","estado": "","cal": 305,"pr": 18.66,"gr": 24.59,"hc": 2.27})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(570),"nombre": "Albahaca","estado": "","cal": 1,"pr": 0.13,"gr": 0.03,"hc": 0.23})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(571),"nombre": "Aguacate","estado": "","cal": 322,"pr": 4.02,"gr": 29.47,"hc": 17.15})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(572),"nombre": "Chutney de mango","estado": "","cal": 182,"pr": 1.26,"gr": 0.98,"hc": 41.27})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(573),"nombre": "Sesamo","estado": "","cal": 322,"pr": 23,"gr": 56,"hc": 1.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(574),"nombre": "Hierbabuena","estado": "","cal": 44,"pr": 3.29,"gr": 0.73,"hc": 8.41})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(575),"nombre": "Cilantro","estado": "","cal": 0,"pr": 0.02,"gr": 0.01,"hc": 0.04})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(576),"nombre": "Menta","estado": "","cal": 70,"pr": 3.75,"gr": 0.49,"hc": 14.89})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(577),"nombre": "Lima","estado": "","cal": 8,"pr": 0.6,"gr": 0.2,"hc": 1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(578),"nombre": "Caldo de marisco","estado": "","cal": 188,"pr": 11.59,"gr": 10.73,"hc": 11.39})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(579),"nombre": "Curry","estado": "","cal": 6,"pr": 0.25,"gr": 0.28,"hc": 1.16})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(580),"nombre": "Carne de cerdo","estado": "","cal": 363,"pr": 36.64,"gr": 22.83,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(581),"nombre": "Pan árabe","estado": "","cal": 123,"pr": 4.05,"gr": 0.53,"hc": 24.82})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(582),"nombre": "Canela","estado": "","cal": 6,"pr": 0.09,"gr": 0.07,"hc": 1.84})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(583),"nombre": "Frijoles","estado": "cocidos","cal": 151,"pr": 5.54,"gr": 5.15,"hc": 21.39})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(584),"nombre": "Cerveza negra","estado": "","cal": 37,"pr": 0.6,"gr": 0,"hc": 5.26})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(585),"nombre": "Cúrcuma","estado": "","cal": 354,"pr": 7.83,"gr": 9.88,"hc": 64.93})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(586),"nombre": "Cardamomo","estado": "","cal": 311,"pr": 10.76,"gr": 6.7,"hc": 68.47})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(587),"nombre": "Macis","estado": "","cal": 475,"pr": 32.4,"gr": 6.7,"hc": 50.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(588),"nombre": "Sobrasada","estado": "","cal": 143,"pr": 3.97,"gr": 13.81,"hc": 0.74})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(589),"nombre": "Vino tinto","estado": "","cal": 85,"pr": 0.07,"gr": 0,"hc": 2.59})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(590),"nombre": "Alcaparra","estado": "","cal": 23,"pr": 2.36,"gr": 0.86,"hc": 4.89})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(591),"nombre": "Oporto","estado": "","cal": 160,"pr": 0.2,"gr": 0,"hc": 13.66})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(592),"nombre": "Pasta fresca","estado": "cocida","cal": 131,"pr": 5.15,"gr": 1.05,"hc": 24.93})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(593),"nombre": "Tomate cherry","estado": "","cal": 18,"pr": 0.88,"gr": 0.2,"hc": 3.92})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(594),"nombre": "Rúcula","estado": "","cal": 25,"pr": 2.58,"gr": 0.66,"hc": 3.65})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(595),"nombre": "Germinados","estado": "","cal": 38,"pr": 2.9,"gr": 0.5,"hc": 5.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(596),"nombre": "Romero","estado": "","cal": 345,"pr": 5,"gr": 15.2,"hc": 46.4})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(597),"nombre": "Coñac","estado": "","cal": 64,"pr": 0,"gr": 0,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(598),"nombre": "Bacon","estado": "","cal": 240,"pr": 15,"gr": 20,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(599),"nombre": "Oregano","estado": "","cal": 306,"pr": 11,"gr": 10.25,"hc": 64.43})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(600),"nombre": "Ensalada de brotes","estado": "","cal": 19,"pr": 2,"gr": 0.4,"hc": 1.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(601),"nombre": "Cebolla morada","estado": "","cal": 40,"pr": 0.89,"gr": 0.08,"hc": 9.74})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(602),"nombre": "Lomo de cerdo ibérico","estado": "","cal": 192,"pr": 22,"gr": 11,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(603),"nombre": "Vinagre de manzana","estado": "","cal": 18,"pr": 0.5,"gr": 0,"hc": 0.5})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(604),"nombre": "Durum","estado": "","cal": 626,"pr": 37.83,"gr": 16.46,"hc": 79.13})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(605),"nombre": "Totopos","estado": "","cal": 476,"pr": 7.6,"gr": 20,"hc": 64})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(606),"nombre": "Ghee (mantequilla clarificada)","estado": "","cal": 876,"pr": 0.28,"gr": 99.48,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(607),"nombre": "Chile serrano","estado": "","cal": 32,"pr": 1.74,"gr": 0.44,"hc": 6.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(608),"nombre": "Anacardo","estado": "","cal": 604,"pr": 22,"gr": 48,"hc": 19})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(609),"nombre": "Salvia molida","estado": "","cal": 315,"pr": 10.6,"gr": 12.8,"hc": 60.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(610),"nombre": "Hinojo","estado": "","cal": 31,"pr": 1.24,"gr": 0.2,"hc": 7.29})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(611),"nombre": "Mozzarella","estado": "","cal": 281,"pr": 22,"gr": 21,"hc": 1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(612),"nombre": "Placa de lasaña/canelon fresca","estado": "","cal": 307,"pr": 11,"gr": 2.9,"hc": 58})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(613),"nombre": "foie","estado": "","cal": 462,"pr": 11.4,"gr": 43.84,"hc": 4.67})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(614),"nombre": "Pesto alla Genovese","estado": "","cal": 482,"pr": 4.7,"gr": 46,"hc": 9.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(615),"nombre": "Pesto rojo","estado": "","cal": 210.81,"pr": 7.57,"gr": 10.44,"hc": 25.55})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(616),"nombre": "Pasta de cabello de ángel","estado": "","cal": 366,"pr": 12,"gr": 1.5,"hc": 74})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(617),"nombre": "Vino rosado","estado": "","cal": 71,"pr": 0.24,"gr": 0,"hc": 4.12})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(618),"nombre": "Cúscus","estado": "","cal": 176,"pr": 5.95,"gr": 0.25,"hc": 36.46})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(619),"nombre": "Cerveza","estado": "","cal": 44,"pr": 0.47,"gr": 0,"hc": 3.6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(620),"nombre": "Cebollino","estado": "","cal": 30,"pr": 3.27,"gr": 0.73,"hc": 4.35})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(621),"nombre": "Caldo de pescado","estado": "","cal": 39,"pr": 4.88,"gr": 1.46,"hc": 0.98})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(622),"nombre": "Pisto sofrito de verduras","estado": "","cal": 82,"pr": 1,"gr": 5.2,"hc": 7.7})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(623),"nombre": "Ras el hanout","estado": "","cal": 377,"pr": 10.9,"gr": 12.1,"hc": 56.3})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(624),"nombre": "Fusilli","estado": "","cal": 359,"pr": 12.5,"gr": 2,"hc": 71.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(625),"nombre": "Tomate seco","estado": "","cal": 225,"pr": 9.1,"gr": 1.3,"hc": 39.8})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(626),"nombre": "Aceitunas negras","estado": "","cal": 105,"pr": 0.88,"gr": 9.54,"hc": 6.06})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(627),"nombre": "Gambones","estado": "","cal": 88,"pr": 18,"gr": 1.8,"hc": 0})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(628),"nombre": "Queso cheddar","estado": "","cal": 403,"pr": 24.9,"gr": 33.14,"hc": 1.28})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(629),"nombre": "Carabineros","estado": "","cal": 113,"pr": 22.83,"gr": 1.49,"hc": 0.9})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(630),"nombre": "Yuca","estado": "","cal": 160,"pr": 1.36,"gr": 0.28,"hc": 38.06})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(631),"nombre": "Boniato","estado": "","cal": 107,"pr": 1.61,"gr": 0.6,"hc": 24.19})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(632),"nombre": "Pimenton dulce","estado": "","cal": 357,"pr": 14.8,"gr": 12.95,"hc": 34.84})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(633),"nombre": "Bimi","estado": "","cal": 33,"pr": 2.85,"gr": 0.37,"hc": 6.41})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(634),"nombre": "Sucedáneo de Angulas","estado": "","cal": 112,"pr": 10,"gr": 4.9,"hc": 6})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(635),"nombre": "Eneldo","estado": "","cal": 292,"pr": 19.9,"gr": 4.4,"hc": 42.2})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(636),"nombre": "Arroz salvaje","estado": "","cal": 335,"pr": 12.6,"gr": 0.9,"hc": 69.1})
db.getCollection('alimentos').insert({"idAlimento": NumberInt(637),"nombre": "Crema de queso","estado": "","cal": 349,"pr": 7.55,"gr": 34.87,"hc": 2.66})
