db.getCollection('recetasimples').insert({id: NumberInt(1), nombre: "Yogur", alimentos: [NumberInt(245)], categoria: ["LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(2), nombre: "Leche con cereales integrales", alimentos: [NumberInt(223), NumberInt(646)], categoria: ["LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(3), nombre: "Pieza de fruta", alimentos: [NumberInt()], categoria: ["FRUTA"]})
db.getCollection('recetasimples').insert({id: NumberInt(4), nombre: "Tostada integral con mantequilla", alimentos: [NumberInt(645), NumberInt(230)], categoria: ["CEREALES", "LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(5), nombre: "Tostada integral con mantequilla y mermelada", alimentos: [NumberInt(645), NumberInt(230), NumberInt(647)], categoria: ["CEREALES", "LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(6), nombre: "Tostada integral con aceite y sal", alimentos: [NumberInt(645), NumberInt(556), NumberInt(547)], categoria: ["CEREALES"]})
db.getCollection('recetasimples').insert({id: NumberInt(7), nombre: "Tostada integral con aguacate", alimentos: [NumberInt(645), NumberInt(556), NumberInt(571), NumberInt(547)], categoria: ["CEREALES", "FRUTA"]})
db.getCollection('recetasimples').insert({id: NumberInt(8), nombre: "Tostada integral con huevo", alimentos: [NumberInt(645), NumberInt(556), NumberInt(252), NumberInt(547)], categoria: ["CEREALES", "HUEVO"]})
db.getCollection('recetasimples').insert({id: NumberInt(9), nombre: "Tostada integral con tomate", alimentos: [NumberInt(645), NumberInt(556), NumberInt(140), NumberInt(547)], categoria: ["CEREALES", "VERDURA"]})
db.getCollection('recetasimples').insert({id: NumberInt(10), nombre: "Tostada integral con atún", alimentos: [NumberInt(645), NumberInt(556), NumberInt(289), NumberInt(547)], categoria: ["CEREALES", "PESCADO"]})
db.getCollection('recetasimples').insert({id: NumberInt(11), nombre: "Huevos revueltos", alimentos: [NumberInt(252), NumberInt(556), NumberInt(547)], categoria: ["HUEVO"]})
db.getCollection('recetasimples').insert({id: NumberInt(12), nombre: "Tortilla", alimentos: [NumberInt(254)], categoria: ["HUEVO"]})
db.getCollection('recetasimples').insert({id: NumberInt(13), nombre: "Zumo de naranja", alimentos: [NumberInt(183)], categoria: ["FRUTA"]})
db.getCollection('recetasimples').insert({id: NumberInt(14), nombre: "Sandwich de pavo con tomate", alimentos: [NumberInt(645), NumberInt(648), NumberInt(140)], categoria: ["CEREALES", "CARNE_BLANCA", "VERDURA"]})
db.getCollection('recetasimples').insert({id: NumberInt(15), nombre: "Sandwich de pavo con queso", alimentos: [NumberInt(645), NumberInt(648), NumberInt(240)], categoria: ["CEREALES", "FRUTA", "LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(16), nombre: "Batido de avena con fruta", alimentos: [NumberInt(223), NumberInt(4)], categoria: ["LACTEOS", "CEREALES", "FRUTA"]})
db.getCollection('recetasimples').insert({id: NumberInt(17), nombre: "Yogur con fruta", alimentos: [NumberInt(244)], categoria: ["LACTEOS", "FRUTA"]})
db.getCollection('recetasimples').insert({id: NumberInt(18), nombre: "Galletas integrales", alimentos: [NumberInt(649)], categoria: ["CEREALES", "LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(19), nombre: "Galletas de chocolate", alimentos: [NumberInt(650)], categoria: ["CEREALES", "LACTEOS", "AZUCARES"]})
db.getCollection('recetasimples').insert({id: NumberInt(20), nombre: "Galletas de avena", alimentos: [NumberInt(651)], categoria: ["CEREALES", "LACTEOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(21), nombre: "Yogur con nueces", alimentos: [NumberInt(215)], categoria: ["LACTEOS", "FRUTOS_SECOS"]})
db.getCollection('recetasimples').insert({id: NumberInt(22), nombre: "Tortitas de arroz integral", alimentos: [NumberInt(215)], categoria: ["CEREALES", "ARROZ_INTEGRAL"]})