export enum CategoriaReceta {
  ARROCES = "ARROCES",
  PASTA = "PASTA",
  PESCADO = "PESCADO",
  CARNE = "CARNE",
  VERDURAS = "VERDURAS"
}

export enum Categoria {
  LACTEOS = "LACTEOS",
  PESCADO = "PESCADO",
  CARNE_BLANCA = "CARNE BLANCA",
  CARNE_ROJA = "CARNE ROJA",
  HUEVO = "HUEVO",
  LEGUMBRES = "LEGUMBRES",
  FRUTOS_SECOS = "FRUTOS SECOS",
  VERDURAS = "VERDURAS",
  FRUTA = "FRUTA",
  PAN_INTEGRAL = "PAN INTEGRAL",
  PASTA_INTEGRAL = "PASTA INTEGRAL",
  ARROZ_INTEGRAL = "ARROZ INTEGRAL",
  PATATAS = "PATATAS",
  AZUCARES = "AZUCARES",
  ACEITE = "ACEITE"
}

export enum Dieta {
  REGULAR = "REGULAR",
  VEGETARIANA = "VEGETARIANA",
  VEGANA = "VEGANA"
}

export enum Frecuencia {
  SEMANAL = 'SEMANAL',
  DIARIA = 'DIARIA',
  OCASIONAL = 'OCASIONAL'
}
